using System;
using System.Data;
using System.Configuration;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using System.IO;
using System.Text;

namespace light
{
   /// <summary>
   /// 01-09区为特殊符号。
   /// 10-15区没有编码
   /// 16-55区为一级汉字，按拼音排序，所以有些取拼音的算法根据这个序来查找，但仅限于一级汉字。（0x10-0x37)
   /// 56-87区为二级汉字，按部首/笔画排序。(0x38- 0x57)
   /// 88-94区没有编码
   /// 每区含94个汉字/编码（ISO 2022的区位码表是94x94的，规定有两个7位的字节来表示汉字，其中又有34个是用来控制，所以每个字节只有128-34=94个编码用于汉字。)
   /// 每个汉字及符号以两个字节来表示。第一个字节称为“高位字节”，第二个字节称为“低位字节”。
   /// 高位字节”使用了0xA1-0xF7(把01-87区的区号加上0xA0)，“低位字节”使用了0xA1-0xFE(把01-94加上0xA0)。
   /// 由于一级汉字是从16区开始的，所以高位字节的范围是(0xB0-0xF7)，低位字节的范围是(0xA1-0xFE)，占用码位是72*94=6768，其中有5个空位是D7F1-D7FE。
   /// 例如“啊”字在大多数程序中，会以0xB0A1储存。（与区位码对比：0xB0=0xA0+16,0xA1=0xA0+1）。
   /// </summary>
   ///<see cref="http://zh.wikipedia.org/wiki/GB2312"/>
   ///<see cref="http://www.dictbox.com/pages/hz.htm"/>
   public sealed class HZ
   {
      #region GB2312中的汉字(6763个，一级汉字3755，二级汉字3008个。)
      
      private static readonly string[][] GB2312 =   new string[][]
      {
         new string[]{"A","啊阿吖嗄腌锕"},
         new string[]{"AI","埃挨哎唉哀皑癌蔼矮艾碍爱隘捱嗳嗌嫒瑷暧砹锿霭"},
         new string[]{"AN","鞍氨安俺按暗岸胺案谙埯揞犴庵桉铵鹌黯"},
         new string[]{"ANG","肮昂盎"},
         new string[]{"AO","凹敖熬翱袄傲奥懊澳坳拗嗷岙廒遨媪骜獒聱螯鏊鳌鏖艹"},
         new string[]{"BA","芭捌扒叭吧笆八疤巴拔跋靶把耙坝霸罢爸茇菝岜灞钯粑鲅魃"},
         new string[]{"BAI","白柏百摆佰败拜稗捭呗掰"},
         new string[]{"BAN","斑班搬扳般颁板版扮拌伴瓣半办绊阪坂钣瘢癍舨"},
         new string[]{"BANG","邦帮梆榜膀绑棒磅蚌镑傍谤蒡浜"},
         new string[]{"BAO","苞胞包褒剥薄雹保堡饱宝抱报暴豹鲍爆葆孢煲鸨褓趵龅勹"},
         new string[]{"BEI","杯碑悲卑北辈背贝钡倍狈备惫焙被孛陂邶埤萆蓓悖碚鹎褙鐾鞴"},
         new string[]{"BEN","奔苯本笨畚坌贲锛"},
         new string[]{"BENG","崩绷甭泵蹦迸嘣甏"},
         new string[]{"BI","逼鼻比鄙笔彼碧蓖蔽毕毙毖币庇痹闭敝弊必辟壁臂避陛匕俾荜荸薜吡哔狴庳愎滗濞弼妣婢嬖璧畀铋秕裨筚箅篦舭襞跸髀"},
         new string[]{"BIAN","鞭边编贬扁便变卞辨辩辫遍匾弁苄忭汴缏飚煸砭碥窆褊蝙笾鳊"},
         new string[]{"BIAO","标彪膘表婊骠杓飑飙镖镳瘭裱鳔髟"},
         new string[]{"BIE","鳖憋别瘪蹩"},
         new string[]{"BIN","彬斌濒滨宾摈傧豳缤玢槟殡膑镔髌鬓"},
         new string[]{"BING","兵冰柄丙秉饼炳病并禀邴摒冫"},
         new string[]{"BO","玻菠播拨钵波博勃搏铂箔伯帛舶脖膊渤泊驳亳啵饽檗擘礴钹鹁簸跛踣"},
         new string[]{"BU","捕卜哺补埠不布步簿部怖卟逋瓿晡钚钸醭"},
         new string[]{"CA","擦嚓礤"},
         new string[]{"CAI","猜裁材才财睬踩采彩菜蔡"},
         new string[]{"CAN","餐参蚕残惭惨灿孱骖璨粲黪"},
         new string[]{"CANG","苍舱仓沧藏"},
         new string[]{"CAO","操糙槽曹草嘈漕螬艚屮"},
         new string[]{"CE","厕策侧册测恻"},
         new string[]{"CEN","岑涔"},
         new string[]{"CENG","层蹭噌"},
         new string[]{"CHA","插叉茬茶查碴搽察岔差诧猹馇汊姹杈楂槎檫锸镲衩"},
         new string[]{"CHAI","拆柴豺侪钗瘥虿"},
         new string[]{"CHAN","搀掺蝉馋谗缠铲产阐颤冁谄谶蒇廛忏潺澶羼婵骣觇禅镡蟾躔"},
         new string[]{"CHANG","昌猖场尝常长偿肠厂敞畅唱倡伥鬯苌菖徜怅惝阊娼嫦昶氅鲳"},
         new string[]{"CHAO","超抄钞朝嘲潮巢吵炒怊晁焯耖"},
         new string[]{"CHE","车扯撤掣彻澈坼砗"},
         new string[]{"CHEN","郴臣辰尘晨忱沉陈趁衬伧谌抻嗔宸琛榇碜龀"},
         new string[]{"CHENG","撑称城橙成呈乘程惩澄诚承逞骋秤丞埕枨柽塍瞠铖裎酲蛏"},
         new string[]{"CHI","吃痴持匙池迟弛驰耻齿侈尺赤翅斥炽傺坻墀茌叱哧啻嗤彳饬媸敕眙眵鸱瘛褫螭笞篪豉踟魑蚩"},
         new string[]{"CHONG","充冲虫崇宠茺忡憧铳舂艟"},
         new string[]{"CHOU","抽酬畴踌稠愁筹仇绸瞅丑臭俦帱惆瘳雠"},
         new string[]{"CHU","初出橱厨躇锄雏滁除楚础储矗搐触处亍刍怵憷绌杵楮樗褚蜍蹰黜"},
         new string[]{"CHUAI","搋啜膪踹"},
         new string[]{"CHUAN","揣川穿椽传船喘串舛遄巛氚钏舡"},
         new string[]{"CHUANG","疮窗幢床闯创怆"},
         new string[]{"CHUI","吹炊捶锤垂陲棰槌"},
         new string[]{"CHUN","春椿醇唇淳纯蠢莼鹑蝽"},
         new string[]{"CHUO","戳绰辍踔龊辶"},
         new string[]{"CI","疵茨磁雌辞慈瓷词此刺赐次茈呲祠鹚糍"},
         new string[]{"CONG","聪葱囱匆从丛苁淙骢琮璁枞"},
         new string[]{"COU","凑楱辏腠"},
         new string[]{"CU","粗醋簇促蔟徂猝殂酢蹙蹴"},
         new string[]{"CUAN","蹿篡窜氽撺爨镩"},
         new string[]{"CUI","摧崔催脆瘁粹淬翠萃啐悴璀榱毳隹"},
         new string[]{"CUN","村存寸忖皴"},
         new string[]{"CUO","磋撮搓措挫错厝嵯脞锉矬痤鹾蹉"},
         new string[]{"DA","搭达答瘩打大耷哒嗒怛妲褡笪靼鞑"},
         new string[]{"DAI","呆歹傣戴带殆代贷袋待逮怠埭甙呔岱迨骀绐玳黛"},
         new string[]{"DAN","耽担丹单郸掸胆旦氮但惮淡诞弹蛋儋萏啖殚赕眈疸瘅聃箪"},
         new string[]{"DANG","当挡党荡档谠凼菪宕砀铛裆"},
         new string[]{"DAO","刀捣蹈倒岛祷导到稻悼道盗刂叨忉氘纛"},
         new string[]{"DE","德得的锝"},
         new string[]{"DENG","蹬灯登等瞪凳邓噔嶝戥磴镫簦"},
         new string[]{"DI","堤低滴迪敌笛狄涤嫡抵底地蒂第帝弟递缔氐籴诋谛邸荻嘀娣绨柢棣觌砥碲睇镝羝骶"},
         new string[]{"DIA","嗲"},
         new string[]{"DIAN","颠掂滇碘点典靛垫电佃甸店惦奠淀殿丶阽坫巅玷钿癜癫簟踮"},
         new string[]{"DIAO","碉叼雕凋刁掉吊钓调铞铫貂鲷"},
         new string[]{"DIE","跌爹碟蝶迭谍叠垤堞揲喋牒瓞耋蹀鲽"},
         new string[]{"DING","丁盯叮钉顶鼎锭定订仃啶玎腚碇町疔耵酊"},
         new string[]{"DIU","丢铥"},
         new string[]{"DONG","东冬董懂动栋侗恫冻洞垌咚岽峒氡胨胴硐鸫"},
         new string[]{"DOU","兜抖斗陡豆逗痘蔸窦蚪篼"},
         new string[]{"DU","都督毒犊独读堵睹赌杜镀肚度渡妒芏嘟渎椟牍蠹笃髑黩"},
         new string[]{"DUAN","端短锻段断缎椴煅簖"},
         new string[]{"DUI","堆兑队对怼憝碓镦"},
         new string[]{"DUN","墩吨蹲敦顿囤钝盾遁沌炖砘礅盹趸"},
         new string[]{"DUO","掇哆多夺垛躲朵跺舵剁惰堕咄哚沲缍柁铎裰踱"},
         new string[]{"E","蛾峨鹅俄额讹娥恶厄扼遏鄂饿噩谔垩苊莪萼呃愕屙婀轭腭锇锷鹗颚鳄"},
         new string[]{"EI","诶"},
         new string[]{"EN","恩蒽摁"},
         new string[]{"ER","而儿耳尔饵洱二贰佴迩珥铒鸸鲕"},
         new string[]{"FA","发罚筏伐乏阀法珐垡砝"},
         new string[]{"FAN","藩帆番翻樊矾钒繁凡烦反返范贩犯饭泛蕃蘩幡梵燔畈蹯"},
         new string[]{"FANG","坊芳方肪房防妨仿访纺放邡枋钫舫鲂"},
         new string[]{"FEI","菲非啡飞肥匪诽吠肺废沸费芾狒悱淝妃绯榧腓斐扉镄痱蜚篚翡霏鲱"},
         new string[]{"FEN","芬酚吩氛分纷坟焚汾粉奋份忿愤粪偾瀵棼鲼鼢"},
         new string[]{"FENG","丰封枫蜂峰锋风疯烽逢冯缝讽奉凤俸酆葑唪沣砜"},
         new string[]{"FOU","否缶"},
         new string[]{"FU","佛夫敷肤孵扶拂辐幅氟符伏俘服浮涪福袱弗甫抚辅俯釜斧脯腑府腐赴副覆赋复傅付阜父腹负富讣附妇缚咐匐凫郛芙苻茯莩菔拊呋幞怫滏艴孚驸绂绋桴赙祓砩黻黼罘稃馥蚨蜉蝠蝮麸趺跗鲋鳆阝"},
         new string[]{"GA","噶嘎尬尕尜旮钆"},
         new string[]{"GAI","该改概钙盖溉丐陔垓戤赅"},
         new string[]{"GAN","干甘杆柑竿肝赶感秆敢赣坩苷尴擀泔淦澉绀橄旰矸疳酐"},
         new string[]{"GANG","冈刚钢缸肛纲岗港杠戆罡筻"},
         new string[]{"GAO","篙皋高膏羔糕搞镐稿告睾诰郜藁缟槔槁杲锆"},
         new string[]{"GE","哥歌搁戈鸽胳疙割革葛格蛤阁隔铬个各鬲仡哿圪塥嗝搿膈硌镉袼虼舸骼"},
         new string[]{"GEI","给"},
         new string[]{"GEN","根跟亘茛哏艮"},
         new string[]{"GENG","耕更庚羹埂耿梗哽赓绠鲠"},
         new string[]{"GONG","工攻功恭龚供躬公宫弓巩汞拱贡共珙肱蚣觥廾"},
         new string[]{"GOU","钩勾沟苟狗垢构购够佝诟岣遘媾缑枸觏彀笱篝鞲"},
         new string[]{"GU","辜菇咕箍估沽孤姑鼓古蛊骨谷股故顾固雇嘏诂菰崮汩梏轱牯牿臌毂瞽罟钴锢鸪痼蛄酤觚鲴鹘"},
         new string[]{"GUA","刮瓜剐寡挂褂卦诖呱栝胍鸹"},
         new string[]{"GUAI","乖拐怪"},
         new string[]{"GUAN","棺关官冠观管馆罐惯灌贯倌莞掼涫盥鹳矜鳏"},
         new string[]{"GUANG","光广逛咣犷桄胱"},
         new string[]{"GUI","瑰规圭硅归龟闺轨鬼诡癸桂柜跪贵刽匦刿庋宄妫桧炅晷皈簋鲑鳜"},
         new string[]{"GUN","辊滚棍衮绲磙鲧"},
         new string[]{"GUO","锅郭国果裹过馘埚掴呙帼崞猓椁虢聒蜾蝈"},
         new string[]{"HA","哈铪"},
         new string[]{"HAI","骸孩海氦亥害骇嗨胲醢"},
         new string[]{"HAN","酣憨邯韩含涵寒函喊罕翰撼捍旱憾悍焊汗汉邗菡撖阚瀚晗焓顸颔蚶鼾"},
         new string[]{"HANG","夯杭航沆绗颃"},
         new string[]{"HAO","壕嚎豪毫郝好耗号浩蒿薅嗥嚆濠灏昊皓颢蚝"},
         new string[]{"HE","呵喝荷菏核禾和何合盒貉阂河涸赫褐鹤贺诃劾壑嗬阖纥曷盍颌蚵翮"},
         new string[]{"HEI","嘿黑"},
         new string[]{"HEN","痕很狠恨"},
         new string[]{"HENG","哼亨横衡恒蘅珩桁"},
         new string[]{"HONG","轰哄烘虹鸿洪宏弘红黉訇讧荭蕻薨闳泓"},
         new string[]{"HOU","喉侯猴吼厚候后堠後逅瘊篌糇鲎骺"},
         new string[]{"HU","呼乎忽瑚壶葫胡蝴狐糊湖弧虎唬护互沪户冱唿囫岵猢怙惚浒滹琥槲轷觳烀煳戽扈祜瓠鹄鹕鹱笏醐斛虍"},
         new string[]{"HUA","花哗华猾滑画划化话骅桦砉铧"},
         new string[]{"HUAI","槐徊怀淮坏踝"},
         new string[]{"HUAN","欢环桓还缓换患唤痪豢焕涣宦幻郇奂萑擐圜獾洹浣漶寰逭缳锾鲩鬟"},
         new string[]{"HUANG","荒慌黄磺蝗簧皇凰惶煌晃幌恍谎隍徨湟潢遑璜肓癀蟥篁鳇"},
         new string[]{"HUI","灰挥辉徽恢蛔回毁悔慧卉惠晦贿秽会烩汇讳诲绘诙茴荟蕙咴哕喙隳洄浍彗缋晖恚虺蟪麾珲"},
         new string[]{"HUN","荤昏婚魂浑混诨馄阍溷"},
         new string[]{"HUO","豁活伙火获或惑霍货祸劐藿攉嚯夥钬锪镬耠蠖灬"},
         new string[]{"JI","击圾基机畸稽积箕肌饥迹激讥鸡姬绩缉吉极棘辑籍集及急疾汲即嫉级挤几脊己蓟技冀季伎祭剂悸济寄寂计记既忌际妓继纪丌亟乩剞佶偈诘墼芨芰荠蒺蕺掎叽咭哜唧岌嵴洎屐骥畿玑楫殛戟戢赍觊犄齑矶羁嵇稷瘠虮笈笄暨跻跽霁鲚鲫髻麂"},
         new string[]{"JIA","嘉枷夹佳家加荚颊贾甲钾假稼价架驾嫁伽郏葭岬浃迦珈戛胛恝铗镓痂瘕袷蛱笳袈跏"},
         new string[]{"JIAN","歼监坚尖笺间煎兼肩艰奸缄茧检柬碱硷拣捡简俭剪减荐槛鉴践贱见键箭件健舰剑饯渐溅涧建僭谏谫菅蒹搛湔蹇謇缣枧楗戋戬牮犍毽腱睑锏鹣裥笕翦趼踺鲣鞯"},
         new string[]{"JIANG","僵姜将浆江疆蒋桨奖讲匠酱降茳洚绛缰犟礓耩糨豇"},
         new string[]{"JIAO","蕉椒礁焦胶交郊浇骄娇嚼搅铰矫侥脚狡角饺缴绞剿教酵轿较叫窖佼僬艽茭挢噍峤徼姣敫皎鹪蛟醮跤鲛"},
         new string[]{"JIE","揭接皆秸街阶截劫节桔杰捷睫竭洁结解姐戒藉芥界借介疥诫届讦拮喈嗟婕孑桀碣疖颉蚧羯鲒骱卩"},
         new string[]{"JIN","巾筋斤金今津襟紧锦仅谨进靳晋禁近烬浸尽劲卺荩堇噤馑廑妗缙瑾槿赆觐衿钅"},
         new string[]{"JING","荆兢茎睛晶鲸京惊精粳经井警景颈静境敬镜径痉靖竟竞净刭儆阱菁獍憬泾迳弪婧肼胫腈旌"},
         new string[]{"JIONG","炯窘冂迥扃"},
         new string[]{"JIU","揪究纠玖韭久灸九酒厩救旧臼舅咎就疚僦啾阄柩桕鸠鹫赳鬏"},
         new string[]{"JU","鞠拘狙疽居驹菊局咀矩举沮聚拒据巨具距踞锯俱句惧炬剧倨讵苣苴莒掬遽屦琚椐榘榉橘犋飓钜锔窭裾趄醵踽龃雎瞿鞫"},
         new string[]{"JUAN","捐鹃娟倦眷卷绢鄄狷涓桊蠲锩镌隽"},
         new string[]{"JUE","撅攫抉掘倔爵觉决诀绝厥劂谲矍蕨噘噱崛獗孓珏桷橛爝镢蹶觖"},
         new string[]{"JUN","均菌钧军君峻俊竣浚郡骏捃皲筠麇"},
         new string[]{"KA","喀咖卡咯佧咔胩"},
         new string[]{"KAI","开揩楷凯慨剀垲蒈忾恺铠锎锴"},
         new string[]{"KAN","刊堪勘坎砍看侃莰戡龛瞰凵"},
         new string[]{"KANG","康慷糠扛抗亢炕伉闶钪"},
         new string[]{"KAO","考拷烤靠尻栲犒铐"},
         new string[]{"KE","坷苛柯棵磕颗科壳咳可渴克刻客课嗑岢恪溘骒缂珂轲氪瞌钶锞稞疴窠颏蝌髁"},
         new string[]{"KEN","肯啃垦恳裉"},
         new string[]{"KENG","坑吭铿"},
         new string[]{"KONG","空恐孔控倥崆箜"},
         new string[]{"KOU","抠口扣寇芤蔻叩眍筘"},
         new string[]{"KU","枯哭窟苦酷库裤刳堀喾绔骷"},
         new string[]{"KUA","夸垮挎跨胯侉"},
         new string[]{"KUAI","块筷侩快蒯郐哙狯脍"},
         new string[]{"KUAN","宽款髋"},
         new string[]{"KUANG","匡筐狂框矿眶旷况诓诳邝圹夼哐纩贶"},
         new string[]{"KUI","亏盔岿窥葵奎魁傀馈愧溃馗匮夔隗蒉揆喹喟悝愦逵暌睽聩蝰篑跬"},
         new string[]{"KUN","坤昆捆困悃阃琨锟醌鲲髡"},
         new string[]{"KUO","括扩廓阔蛞"},
         new string[]{"LA","垃拉喇蜡腊辣啦剌邋旯砬瘌"},
         new string[]{"LAI","莱来赖崃徕涞濑赉睐铼癞籁"},
         new string[]{"LAN","蓝婪栏拦篮阑兰澜谰揽览懒缆烂滥岚漤榄斓罱镧褴"},
         new string[]{"LANG","琅榔狼廊郎朗浪莨蒗啷阆锒稂螂"},
         new string[]{"LAO","捞劳牢老佬姥酪烙涝唠崂栳铑铹痨耢醪"},
         new string[]{"LE","勒乐仂叻泐鳓"},
         new string[]{"LEI","雷镭蕾磊累儡垒擂肋类泪羸诔嘞嫘缧檑耒酹"},
         new string[]{"LENG","棱楞冷塄愣"},
         new string[]{"LI","厘梨犁黎篱狸离漓理李里鲤礼莉荔吏栗丽厉励砾历利傈例俐痢立粒沥隶力璃哩俪俚郦坜苈莅蓠藜呖唳喱猁溧澧逦娌嫠骊缡枥栎轹戾砺詈罹锂鹂疠疬蛎蜊蠡笠篥粝醴跞雳鲡鳢黧"},
         new string[]{"LIA","俩"},
         new string[]{"LIAN","联莲连镰廉怜涟帘敛脸链恋炼练蔹奁潋濂琏楝殓臁裢裣蠊鲢"},
         new string[]{"LIANG","粮凉梁粱良两辆量晾亮谅墚椋踉靓魉"},
         new string[]{"LIAO","撩聊僚疗燎寥辽潦了撂镣廖料蓼尥嘹獠寮缭钌鹩"},
         new string[]{"LIE","列裂烈劣猎冽埒捩咧洌趔躐鬣"},
         new string[]{"LIN","琳林磷霖临邻鳞淋凛赁吝蔺啉嶙廪懔遴檩辚膦瞵粼躏麟"},
         new string[]{"LING","拎玲菱零龄铃伶羚凌灵陵岭领另令酃苓呤囹泠绫柃棂瓴聆蛉翎鲮"},
         new string[]{"LIU","溜琉榴硫馏留刘瘤流柳六浏遛骝绺旒熘锍镏鹨鎏"},
         new string[]{"LONG","龙聋咙笼窿隆垄拢陇垅茏泷珑栊胧砻癃"},
         new string[]{"LOU","楼娄搂篓漏陋偻蒌喽嵝镂瘘耧蝼髅"},
         new string[]{"LU","芦卢颅庐炉掳卤虏鲁麓碌露路赂鹿潞禄录陆戮驴吕铝侣旅履屡缕虑氯律率滤绿垆捋撸噜闾泸渌漉逯璐栌榈橹轳辂辘氇胪膂镥稆鸬鹭褛簏舻鲈"},
         new string[]{"LUAN","峦挛孪滦卵乱脔娈栾鸾銮"},
         new string[]{"LUE","掠略锊"},
         new string[]{"LUN","抡轮伦仑沦纶论囵"},
         new string[]{"LUO","萝螺罗逻锣箩骡裸落洛骆络倮蠃荦摞猡泺漯珞椤脶镙瘰雒"},
         new string[]{"M","呒"},
         new string[]{"MA","妈麻玛码蚂马骂嘛吗唛犸嬷杩蟆"},
         new string[]{"MAI","埋买麦卖迈脉劢荬霾"},
         new string[]{"MAN","瞒馒蛮满蔓曼慢漫谩墁幔缦熳镘颟螨鳗鞔"},
         new string[]{"MANG","芒茫盲氓忙莽邙漭硭蟒"},
         new string[]{"MAO","猫茅锚毛矛铆卯茂冒帽貌贸袤茆峁泖瑁昴牦耄旄懋瞀蟊髦"},
         new string[]{"ME","么麽"},
         new string[]{"MEI","玫枚梅酶霉煤没眉媒镁每美昧寐妹媚莓嵋猸浼湄楣镅鹛袂魅"},
         new string[]{"MEN","门闷们扪焖懑钔"},
         new string[]{"MENG","萌蒙檬盟锰猛梦孟勐甍瞢懵朦礞虻蜢蠓艋艨"},
         new string[]{"MI","眯醚靡糜迷谜弥米秘觅泌蜜密幂芈谧蘼咪嘧猕汨宓弭脒祢敉糸縻麋冖"},
         new string[]{"MIAN","棉眠绵冕免勉娩缅面沔渑湎腼眄黾宀"},
         new string[]{"MIAO","苗描瞄藐秒渺庙妙喵邈缈缪杪淼眇鹋"},
         new string[]{"MIE","蔑灭咩蠛篾"},
         new string[]{"MIN","民抿皿敏悯闽苠岷闵泯缗玟珉愍鳘"},
         new string[]{"MING","明螟鸣铭名命冥茗溟暝瞑酩"},
         new string[]{"MIU","谬"},
         new string[]{"MO","摸摹蘑模膜磨摩魔抹末莫墨默沫漠寞陌谟茉蓦馍嫫殁镆秣瘼耱貊貘"},
         new string[]{"MOU","谋牟某侔哞眸蛑蝥鍪"},
         new string[]{"MU","拇牡亩姆母墓暮幕募慕木目睦牧穆仫坶苜沐毪钼"},
         new string[]{"NA","拿哪呐钠那娜纳捺肭镎衲"},
         new string[]{"NAI","氖乃奶耐奈鼐艿萘柰"},
         new string[]{"NAN","南男难喃囝囡楠腩蝻赧"},
         new string[]{"NANG","囊攮囔馕曩"},
         new string[]{"NAO","挠脑恼闹淖孬垴呶猱瑙硇铙蛲"},
         new string[]{"NE","呢讷疒"},
         new string[]{"NEI","馁内"},
         new string[]{"NEN","嫩恁"},
         new string[]{"NENG","能"},
         new string[]{"NG","嗯"},
         new string[]{"NI","妮霓倪泥尼拟你匿腻逆溺伲坭猊怩昵旎慝睨铌鲵"},
         new string[]{"NIAN","蔫拈年碾撵捻念廿埝辇黏鲇鲶"},
         new string[]{"NIANG","娘酿"},
         new string[]{"NIAO","鸟尿茑嬲脲袅"},
         new string[]{"NIE","捏聂孽啮镊镍涅乜陧蘖嗫颞臬蹑"},
         new string[]{"NIN","您"},
         new string[]{"NING","柠狞凝宁拧泞佞苎咛甯聍"},
         new string[]{"NIU","牛扭钮纽狃忸妞"},
         new string[]{"NONG","脓浓农弄侬哝"},
         new string[]{"NOU","耨"},
         new string[]{"NU","奴努怒女弩胬孥驽恧钕衄"},
         new string[]{"NUAN","暖"},
         new string[]{"NUE","虐疟"},
         new string[]{"NUO","挪懦糯诺傩搦喏锘"},
         new string[]{"O","哦喔噢"},
         new string[]{"OU","欧鸥殴藕呕偶沤讴怄瓯耦"},
         new string[]{"PA","啪趴爬帕怕琶葩杷筢"},
         new string[]{"PAI","拍排牌徘湃派俳蒎哌"},
         new string[]{"PAN","攀潘盘磐盼畔判叛爿泮袢襻蟠蹒丬"},
         new string[]{"PANG","乓庞旁耪胖彷滂逄螃"},
         new string[]{"PAO","抛咆刨炮袍跑泡匏狍庖脬疱"},
         new string[]{"PEI","呸胚培裴赔陪配佩沛辔帔旆锫醅霈"},
         new string[]{"PEN","喷盆湓"},
         new string[]{"PENG","砰抨烹澎彭蓬棚硼篷膨朋鹏捧碰堋嘭怦蟛"},
         new string[]{"PI","坯砒霹批披劈琵毗啤脾疲皮匹痞僻屁譬丕仳陴邳郫圮鼙芘擗噼庀淠媲纰枇甓睥罴铍癖疋蚍蜱貔"},
         new string[]{"PIAN","篇偏片骗谝骈犏胼翩蹁"},
         new string[]{"PIAO","飘漂瓢票剽嘌嫖缥殍瞟螵"},
         new string[]{"PIE","撇瞥丿苤氕"},
         new string[]{"PIN","拼频贫品聘拚姘嫔榀牝颦"},
         new string[]{"PING","乒坪苹萍平凭瓶评屏俜娉枰鲆"},
         new string[]{"PO","坡泼颇婆破魄迫粕叵鄱珀攴钋钷皤笸"},
         new string[]{"POU","剖裒掊"},
         new string[]{"PU","扑铺仆莆葡菩蒲埔朴圃普浦谱曝瀑匍噗溥濮璞氆镤镨蹼攵"},
         new string[]{"QI","期欺栖戚妻七凄漆柒沏其棋奇歧畦崎脐齐旗祈祁骑起岂乞企启契砌器气迄弃汽泣讫亓俟圻芑芪萁萋葺蕲嘁屺岐汔淇骐绮琪琦杞桤槭耆欹祺憩碛颀蛴蜞綦綮蹊鳍麒"},
         new string[]{"QIA","掐恰洽葜髂"},
         new string[]{"QIAN","牵扦钎铅千迁签仟谦乾黔钱钳前潜遣浅谴堑嵌欠歉倩佥阡芊芡茜荨掮岍悭慊骞搴褰缱椠肷愆钤虔箬箝"},
         new string[]{"QIANG","枪呛腔羌墙蔷强抢戕嫱樯戗炝锖锵镪襁蜣羟跄"},
         new string[]{"QIAO","橇锹敲悄桥瞧乔侨巧鞘撬翘峭俏窍劁诮谯荞愀憔樵硗跷鞒"},
         new string[]{"QIE","切茄且怯窃郄惬妾挈锲箧"},
         new string[]{"QIN","钦侵亲秦琴勤芹擒禽寝沁芩揿吣嗪噙溱檎锓覃螓衾"},
         new string[]{"QING","青轻氢倾卿清擎晴氰情顷请庆苘圊檠磬蜻罄箐謦鲭黥"},
         new string[]{"QIONG","琼穷邛茕穹蛩筇跫銎"},
         new string[]{"QIU","秋丘邱球求囚酋泅俅巯犰湫逑遒楸赇虬蚯蝤裘糗鳅鼽"},
         new string[]{"QU","趋区蛆曲躯屈驱渠取娶龋趣去诎劬蕖蘧岖衢阒璩觑氍朐祛磲鸲癯蛐蠼麴黢"},
         new string[]{"QUAN","圈颧权醛泉全痊拳犬券劝诠荃悛绻辁畎铨蜷筌鬈犭"},
         new string[]{"QUE","缺炔瘸却鹊榷确雀阕阙悫"},
         new string[]{"QUN","裙群逡"},
         new string[]{"RAN","然燃冉染苒蚺髯"},
         new string[]{"RANG","瓤壤攘嚷让禳穰"},
         new string[]{"RAO","饶扰绕荛娆桡"},
         new string[]{"RE","惹热"},
         new string[]{"REN","壬仁人忍韧任认刃妊纫亻仞荏葚饪轫稔衽"},
         new string[]{"RENG","扔仍"},
         new string[]{"RI","日"},
         new string[]{"RONG","戎茸蓉荣融熔溶容绒冗嵘狨榕肜蝾"},
         new string[]{"ROU","揉柔肉糅蹂鞣"},
         new string[]{"RU","茹蠕儒孺如辱乳汝入褥蓐薷嚅洳溽濡缛铷襦颥"},
         new string[]{"RUAN","软阮朊"},
         new string[]{"RUI","蕊瑞锐芮蕤枘睿蚋"},
         new string[]{"RUN","闰润"},
         new string[]{"RUO","若弱偌"},
         new string[]{"SA","撒洒萨卅仨挲脎飒"},
         new string[]{"SAI","腮鳃塞赛噻"},
         new string[]{"SAN","三叁伞散馓毵糁"},
         new string[]{"SANG","桑嗓丧搡磉颡"},
         new string[]{"SAO","搔骚扫嫂埽缫缲臊瘙鳋"},
         new string[]{"SE","瑟色涩啬铯穑"},
         new string[]{"SEN","森"},
         new string[]{"SENG","僧"},
         new string[]{"SHA","莎砂杀刹沙纱傻啥煞唼歃铩痧裟霎鲨"},
         new string[]{"SHAI","筛晒酾"},
         new string[]{"SHAN","珊苫杉山删煽衫闪陕擅赡膳善汕扇缮剡讪鄯埏芟潸姗嬗骟膻钐疝蟮舢跚鳝彡"},
         new string[]{"SHANG","墒伤商赏晌上尚裳垧绱殇熵觞"},
         new string[]{"SHAO","梢捎稍烧芍勺韶少哨邵绍劭苕潲蛸筲艄"},
         new string[]{"SHE","奢赊蛇舌舍赦摄射慑涉社设厍佘猞滠歙畲麝"},
         new string[]{"SHEN","什砷申呻伸身深娠绅神沈审婶甚肾慎渗诜谂莘哂渖椹胂矧蜃"},
         new string[]{"SHENG","声生甥牲升绳省盛剩胜圣嵊晟眚笙"},
         new string[]{"SHI","师失狮施湿诗尸虱十石拾时食蚀实识史矢使屎驶始式示士世柿事拭誓逝势是嗜噬适仕侍释饰氏市恃室视试谥埘莳蓍弑饣轼贳炻铈螫舐筮豕鲥鲺礻"},
         new string[]{"SHOU","收手首守寿授售受瘦兽狩绶艏扌"},
         new string[]{"SHU","蔬枢梳殊抒输叔舒淑疏书赎孰熟薯暑曙署蜀黍鼠属术述树束戍竖墅庶数漱恕丨倏塾菽摅沭澍姝纾毹腧殳秫"},
         new string[]{"SHUA","刷耍唰"},
         new string[]{"SHUAI","摔衰甩帅蟀"},
         new string[]{"SHUAN","栓拴闩涮"},
         new string[]{"SHUANG","霜双爽孀"},
         new string[]{"SHUI","谁水睡税氵"},
         new string[]{"SHUN","吮瞬顺舜"},
         new string[]{"SHUO","说硕朔烁蒴搠妁槊铄"},
         new string[]{"SI","斯撕嘶思私司丝死肆寺嗣四伺似饲巳厮兕厶咝汜泗澌姒驷缌祀锶鸶耜蛳笥纟"},
         new string[]{"SONG","松耸怂颂送宋讼诵凇菘崧嵩忪悚淞竦"},
         new string[]{"SOU","搜艘擞嗽叟薮嗖嗾馊溲飕瞍锼螋"},
         new string[]{"SU","苏酥俗素速粟僳塑溯宿诉肃夙谡蔌嗉愫涑簌觫稣"},
         new string[]{"SUAN","酸蒜算狻"},
         new string[]{"SUI","虽隋随绥髓碎岁穗遂隧祟谇荽濉邃燧眭睢"},
         new string[]{"SUN","孙损笋荪狲飧榫隼"},
         new string[]{"SUO","蓑梭唆缩琐索锁所唢嗦嗍娑桫睃羧"},
         new string[]{"TA","塌他它她塔獭挞蹋踏闼溻遢榻沓铊趿鳎"},
         new string[]{"TAI","胎苔抬台泰酞太态汰邰薹肽炱钛跆鲐"},
         new string[]{"TAN","坍摊贪瘫滩坛檀痰潭谭谈坦毯袒碳探叹炭郯澹昙忐钽锬"},
         new string[]{"TANG","汤塘搪堂棠膛唐糖倘躺淌趟烫傥帑溏瑭樘铴镗耥螗螳羰醣"},
         new string[]{"TAO","掏涛滔绦萄桃逃淘陶讨套鼗啕洮韬焘饕"},
         new string[]{"TE","特忒忑铽"},
         new string[]{"TENG","藤腾疼誊滕"},
         new string[]{"TI","梯剔踢锑提题蹄啼体替嚏惕涕剃屉倜悌逖缇鹈裼醍"},
         new string[]{"TIAN","天添填田甜恬舔腆掭忝阗殄畋"},
         new string[]{"TIAO","挑条迢眺跳佻祧窕蜩笤粜龆鲦髫"},
         new string[]{"TIE","贴铁帖萜餮"},
         new string[]{"TING","厅听烃汀廷停亭庭挺艇莛葶婷梃铤蜓霆"},
         new string[]{"TONG","通桐酮瞳同铜彤童桶捅筒统痛佟仝茼嗵恸潼砼"},
         new string[]{"TOU","偷投头透钭骰亠"},
         new string[]{"TU","凸秃突图徒途涂屠土吐兔堍荼菟钍酴"},
         new string[]{"TUAN","湍团抟彖疃"},
         new string[]{"TUI","推颓腿蜕褪退煺"},
         new string[]{"TUN","吞屯臀氽饨暾豚"},
         new string[]{"TUO","拖托脱鸵陀驮驼椭妥拓唾乇佗坨庹沱柝橐砣箨酡跎鼍"},
         new string[]{"WA","挖哇蛙洼娃瓦袜佤娲腽"},
         new string[]{"WAI","歪外"},
         new string[]{"WAN","豌弯湾玩顽丸烷完碗挽晚皖惋宛婉万腕剜芄菀纨绾琬脘畹蜿"},
         new string[]{"WANG","汪王亡枉网往旺望忘妄罔尢惘辋魍"},
         new string[]{"WEI","威巍微危韦违桅围唯惟为潍维苇萎委伟伪尾纬未蔚味畏胃喂魏位渭谓尉慰卫偎诿隈葳薇囗帏帷崴嵬猥猬闱沩洧涠逶娓玮韪軎炜煨痿艉鲔"},
         new string[]{"WEN","瘟温蚊文闻纹吻稳紊问刎阌汶璺雯"},
         new string[]{"WENG","嗡翁瓮蓊蕹"},
         new string[]{"WO","挝蜗涡窝我斡卧握沃倭莴幄渥肟硪龌"},
         new string[]{"WU","巫呜钨乌污诬屋无芜梧吾吴毋武五捂午舞伍侮坞戊雾晤物勿务悟误兀仵阢邬圬芴唔庑怃忤浯寤迕妩婺骛杌牾焐鹉鹜痦蜈鋈鼯"},
         new string[]{"XI","昔熙析西硒矽晰嘻吸锡牺稀息希悉膝夕惜熄烯溪汐犀檄袭席习媳喜铣洗系隙戏细僖兮隰郗菥葸蓰奚唏徙饩阋浠淅屣嬉玺樨曦觋欷熹禊禧皙穸蜥螅蟋舄舾羲粞翕醯鼷"},
         new string[]{"XIA","瞎虾匣霞辖暇峡侠狭下厦夏吓呷狎遐瑕柙硖罅黠"},
         new string[]{"XIAN","掀锨先仙鲜纤咸贤衔舷闲涎弦嫌显险现献县腺馅羡宪陷限线冼苋莶藓岘猃暹娴氙燹祆鹇痫蚬筅籼酰跣跹霰"},
         new string[]{"XIANG","相厢镶香箱襄湘乡翔祥详想响享项巷橡像向象芗葙饷庠骧缃蟓鲞飨"},
         new string[]{"XIAO","萧硝霄削哮嚣销消宵淆晓小孝校肖啸笑效哓崤潇逍骁绡枭枵筱箫魈"},
         new string[]{"XIE","楔些歇蝎鞋协挟携邪斜胁谐写械卸蟹懈泄泻谢屑偕亵勰燮薤撷獬廨渫瀣邂绁缬榭榍躞"},
         new string[]{"XIN","薪芯锌欣辛新忻心信衅囟馨昕歆鑫忄"},
         new string[]{"XING","星腥猩惺兴刑型形邢行醒幸杏性姓陉荇荥擤饧悻硎"},
         new string[]{"XIONG","兄凶胸匈汹雄熊芎"},
         new string[]{"XIU","休修羞朽嗅锈秀袖绣咻岫馐庥溴鸺貅髹"},
         new string[]{"XU","墟戌需虚嘘须徐许蓄酗叙旭序畜恤絮婿绪续诩勖圩蓿洫溆顼栩煦盱胥糈醑"},
         new string[]{"XUAN","轩喧宣悬旋玄选癣眩绚儇谖萱揎泫渲漩璇楦暄炫煊碹铉镟痃"},
         new string[]{"XUE","靴薛学穴雪血谑泶踅鳕彐"},
         new string[]{"XUN","勋熏循旬询寻驯巡殉汛训讯逊迅巽埙荀蕈薰峋徇獯恂洵浔曛醺鲟"},
         new string[]{"YA","压押鸦鸭呀丫芽牙蚜崖衙涯雅哑亚讶伢垭揠岈迓娅琊桠氩砑睚痖"},
         new string[]{"YAN","焉咽阉烟淹盐严研蜒岩延言颜阎炎沿奄掩眼衍演艳堰燕厌砚雁唁彦焰宴谚验厣赝匚俨偃兖谳郾鄢菸崦恹闫阏湮滟妍嫣琰檐晏胭焱罨筵酽魇餍鼹讠"},
         new string[]{"YANG","殃央鸯秧杨扬佯疡羊洋阳氧仰痒养样漾徉怏泱炀烊恙蛘鞅"},
         new string[]{"YAO","邀腰妖瑶摇尧遥窑谣姚咬舀药要耀夭爻吆崾徭幺珧杳轺曜肴鹞窈繇鳐"},
         new string[]{"YE","椰噎耶爷野冶也页掖业叶曳腋夜液靥谒揶晔烨铘邺"},
         new string[]{"YI","一壹医揖铱依伊衣颐夷遗移仪胰疑沂宜姨彝椅蚁倚已乙矣以艺抑易邑屹亿役臆逸肄疫亦裔意毅忆义益溢诣议谊译异翼翌绎刈劓佚佾诒圯埸懿苡荑薏弈奕挹弋呓咦咿噫峄嶷猗饴怿怡悒漪迤驿缢殪轶贻旖熠钇镒镱痍瘗癔翊蜴舣羿翳酏黟衤"},
         new string[]{"YIN","茵荫因殷音阴姻吟银淫寅饮尹引隐印胤鄞垠堙茚吲喑狺夤洇氤铟瘾窨蚓霪龈廴"},
         new string[]{"YING","英樱婴鹰应缨莹萤营荧蝇迎赢盈影颖硬映嬴郢茔莺萦撄嘤膺滢潆瀛瑛璎楹媵鹦瘿颍罂蓥"},
         new string[]{"YO","哟唷"},
         new string[]{"YONG","拥佣臃痈庸雍踊蛹咏泳涌永恿勇用俑壅墉喁慵邕镛甬鳙饔"},
         new string[]{"YOU","幽优悠忧尤由邮铀犹油游酉有友右佑釉诱又幼卣攸侑莠莜莸呦囿宥柚猷牖铕疣蚰蚴蝣鱿黝鼬"},
         new string[]{"YU","迂淤于盂榆虞愚舆余俞逾鱼愉渝渔隅予娱雨与屿禹宇语羽玉域芋郁吁遇喻峪御愈欲狱育誉浴寓裕预豫驭禺毓伛俣谀谕萸蓣揄圄圉嵛狳饫馀庾阈鬻妪妤纡肀瑜昱觎腴欤於煜燠聿钰鹆鹬瘐瘀窳蜮蝓竽臾舁雩龉窬"},
         new string[]{"YUAN","鸳渊冤元垣袁原援辕园员圆猿源缘远苑愿怨院垸塬芫掾沅媛瑗橼爰眢鸢螈箢鼋"},
         new string[]{"YUE","曰约越跃钥岳粤月悦阅龠瀹樾刖钺"},
         new string[]{"YUN","耘云郧匀陨允运蕴酝晕韵孕郓芸狁恽愠纭韫殒昀氲熨"},
         new string[]{"ZA","匝砸杂拶咂"},
         new string[]{"ZAI","翟栽哉灾宰载再在崽甾"},
         new string[]{"ZAN","咱攒暂赞瓒昝簪糌趱錾"},
         new string[]{"ZANG","赃脏葬奘驵臧"},
         new string[]{"ZAO","遭糟凿藻枣早澡蚤躁噪造皂灶燥唣"},
         new string[]{"ZE","责择则泽仄赜啧帻迮昃笮箦舴"},
         new string[]{"ZEI","贼"},
         new string[]{"ZEN","怎谮"},
         new string[]{"ZENG","增憎曾赠缯甑罾锃"},
         new string[]{"ZHA","扎喳渣札轧铡闸眨栅榨咋乍炸诈揸吒咤哳砟痄蚱齄"},
         new string[]{"ZHAI","摘斋宅窄债寨砦瘵"},
         new string[]{"ZHAN","瞻毡詹粘沾盏斩辗崭展蘸栈占战站湛绽谵搌旃"},
         new string[]{"ZHANG","樟章彰漳张掌涨杖丈帐账仗胀瘴障仉鄣幛嶂獐嫜璋蟑"},
         new string[]{"ZHAO","招昭找沼赵照罩兆肇召诏棹钊笊"},
         new string[]{"ZHE","遮折哲蛰辙者锗蔗这浙谪摺柘辄磔鹧褶蜇赭"},
         new string[]{"ZHEN","珍斟真甄砧臻贞针侦枕疹诊震振镇阵圳蓁浈缜桢榛轸赈胗朕祯畛稹鸩箴"},
         new string[]{"ZHENG","蒸挣睁征狰争怔整拯正政帧症郑证诤峥徵钲铮筝"},
         new string[]{"ZHI","芝枝支吱蜘知肢脂汁之织职直植殖执值侄址指止趾只旨纸志挚掷至致置帜峙制智秩稚质炙痔滞治窒卮陟郅埴芷摭帙忮彘咫骘栉枳栀桎轵轾贽胝膣祉祗黹雉鸷痣蛭絷酯跖踬踯豸觯"},
         new string[]{"ZHONG","中盅忠钟衷终种肿重仲众冢锺螽舯踵夂"},
         new string[]{"ZHOU","舟周州洲诌粥轴肘帚咒皱宙昼骤荮啁妯纣绉胄碡籀酎"},
         new string[]{"ZHU","珠株蛛朱猪诸诛逐竹烛煮拄瞩嘱主著柱助蛀贮铸筑住注祝驻伫侏邾茱洙渚潴杼槠橥炷铢疰瘃竺箸舳翥躅麈"},
         new string[]{"ZHUA","抓爪"},
         new string[]{"ZHUAI","拽"},
         new string[]{"ZHUAN","专砖转撰赚篆啭馔颛"},
         new string[]{"ZHUANG","桩庄装妆撞壮状僮"},
         new string[]{"ZHUI","椎锥追赘坠缀惴骓缒"},
         new string[]{"ZHUN","谆准肫窀"},
         new string[]{"ZHUO","捉拙卓桌琢茁酌啄着灼浊倬诼擢浞涿濯禚斫镯"},
         new string[]{"ZI","兹咨资姿滋淄孜紫仔籽滓子自渍字谘嵫姊孳缁梓辎赀恣眦锱秭耔笫粢趑觜訾龇鲻髭"},
         new string[]{"ZONG","鬃棕踪宗综总纵偬腙粽"},
         new string[]{"ZOU","邹走奏揍诹陬鄹驺鲰"},
         new string[]{"ZU","租足卒族祖诅阻组俎菹镞"},
         new string[]{"ZUAN","钻纂攥缵躜"},
         new string[]{"ZUI","嘴醉最罪蕞"},
         new string[]{"ZUN","尊遵撙樽鳟"},
         new string[]{"ZUO","昨左佐柞做作坐座阼唑嘬怍胙祚"}
   };
      #endregion

      public static string ToPinYin(string str, bool handleSpace = false,bool hyphen=false)
      {
         if (string.IsNullOrEmpty(str)) return string.Empty;
         Encoding ed = Encoding.GetEncoding("GB2312");
         if (ed == null) throw (new ArgumentException("没有找到编码集GB2312"));
         string pinyin = string.Empty;
         str = SU.MergeSpace(str).Trim();
         char lastchar = ' ';

         foreach (char c in str)
         {
            if (handleSpace && c == ' ' && lastchar != ' ')
            {
               pinyin += "-";
               lastchar = c;
            }

            byte[] bAry = ed.GetBytes(c.ToString());
            if (bAry.Length == 1) //【判断下是否是字母】
            {
               if (char.IsLetterOrDigit(c))
               {
                  if (hyphen && pinyin != string.Empty && !char.IsLetterOrDigit(lastchar)) pinyin += "-";
                  pinyin += c;
                  lastchar = c;
               }
               continue;
            }

            int bh = bAry[0];
            if (0xB0 <= bh && bh <= 0xF7)//是gb2312汉字
            {
               for (int i = 0; i < GB2312.Length; i++)
               {
                  if (GB2312[i][1].IndexOf(c) != -1)
                  {
                     if (hyphen && pinyin != string.Empty) pinyin += "-";
                     pinyin += GB2312[i][0];
                     lastchar = c;
                     break;
                  }
               }
            }
         }

         return pinyin.ToLower();
      }
   }
}